### ISSUE TITLE
doesn't run on windows

### ISSUE THREAD

**Issue by jtippett** [raurir/AnsiBot#1]
i am trying to run this game on my windows XP computer and it doesn't work. help plz?

**Comment by raurir** [comment]
Hi @jtippett 

This isn't actually a game, but you can make it a game by trying to run it on windows xp. That should be very fun.

Enjoy Level 1!

**Comment by raurir** [comment]
@jtippett three and a half years have gone by, did you work out how to make it work on your windows box?

**Comment by raurir** [comment]
@jtippett checking again 3 years later...
